/// This is the implementation of the `inf:wasi/config` interface but only
/// intended for manual testing purposes and not for production use.
///
/// The idea is that this type of implementation would be generated by a tool.
use crate::exports::inf::wasi::config::Guest;
use crate::exports::inf::wasi::config_types::Config;
use std::path::PathBuf;

wit_bindgen::generate!({
    path: "../wit/inf.wit",
    world: "config-world",
});

struct Exports;

impl Guest for Exports {
    fn get_config() -> Config {
        let model_path = PathBuf::from("models/llama-2-7b-chat.Q5_K_M.gguf")
            .to_str()
            .unwrap()
            .to_string();
        Config {
            model_path,
            prompt: "What is the capital of Sweden?".to_string(),
        }
    }
}

export!(Exports);
