[package]
name = "generator-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
clap = { version = "4.3.11", features = ["derive"]}
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
generator = { path = ".." }

[workspace]
