[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
wit-bindgen = { version = "0.19.2", default-features = true, features = ['macros'] }

[lib]
crate-type = ["cdylib"]
