[package]
name = "inference"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
wit-bindgen = { version = "0.19.2", default-features = true, features = ['macros'] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
debug-assertions = false
